// Supabase Edge Function: generate-release-notes
//
// DUMMY worker for now: validates the request, returns 202 immediately, and
// does the slow work in the background (EdgeRuntime.waitUntil) so neither this
// request nor the user's web request blocks for 30s. After the delay it writes
// the generated markdown to Storage and flips the release_notes row to 'draft'.
//
// All DB/Storage work runs with the *caller's* JWT (the `authenticated` role),
// which has the table grants + RLS access + storage-folder access it needs.
// NOTE: the future webhook trigger has no user JWT, so that path will need a
// service identity (grant the relevant role on release_notes) instead.
//
// TODO(real generation): replace the delay + buildDummyMarkdown with
//   1. fetch the tag range via GitHub (compare / generate-notes) using installationId
//   2. summarise via the Anthropic API
//
// Deploy: supabase functions deploy generate-release-notes
// (verify_jwt defaults to true, so the caller's user JWT is required.)

import { createClient, type SupabaseClient } from 'https://esm.sh/@supabase/supabase-js@2';

declare const EdgeRuntime: { waitUntil(promise: Promise<unknown>): void };

type GeneratePayload = {
  releaseNoteId: string;
  repositoryFullName: string;
  owner: string;
  repo: string;
  installationId: number;
  startTag: string;
  endTag: string;
  storagePath: string;
};

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY')!;

const DUMMY_DELAY_MS = 30_000;

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json' }
  });

function buildDummyMarkdown(payload: GeneratePayload): string {
  return [
    `# ${payload.repositoryFullName} ${payload.endTag}`,
    '',
    `_Release notes generated from ${payload.startTag} to ${payload.endTag}._`,
    '',
    '## ✨ Features',
    '- _Placeholder feature summary (dummy worker)._',
    '',
    '## 🐛 Fixes',
    '- _Placeholder fix summary (dummy worker)._',
    '',
    '---',
    '> Generated by the ShipLog dummy worker. Real GitHub + AI generation coming soon.',
    ''
  ].join('\n');
}

async function runGeneration(db: SupabaseClient, payload: GeneratePayload) {
  try {
    // Simulate the cost of fetching commits + calling the model.
    await new Promise((resolve) => setTimeout(resolve, DUMMY_DELAY_MS));

    const markdown = buildDummyMarkdown(payload);

    const { error: uploadError } = await db.storage
      .from('release-notes')
      .upload(payload.storagePath, markdown, { contentType: 'text/markdown', upsert: true });
    if (uploadError) throw uploadError;

    // Only mark draft if the note is still awaiting generation. If it was
    // deleted (or otherwise changed) mid-run, this touches 0 rows — so clean
    // up the file we just uploaded instead of leaving an orphan in Storage.
    const { data: updated, error: updateError } = await db
      .from('release_notes')
      .update({ status: 'draft', error_message: null })
      .eq('id', payload.releaseNoteId)
      .eq('status', 'generating')
      .select('id');
    if (updateError) throw updateError;

    if (!updated || updated.length === 0) {
      await db.storage.from('release-notes').remove([payload.storagePath]);
    }
  } catch (err) {
    console.error('Release note generation failed', err);
    // Best-effort: only flip to failed if the note is still around and generating.
    await db
      .from('release_notes')
      .update({ status: 'failed', error_message: String((err as Error)?.message ?? err) })
      .eq('id', payload.releaseNoteId)
      .eq('status', 'generating');
  }
}

Deno.serve(async (req) => {
  if (req.method !== 'POST') {
    return json({ error: 'Method not allowed' }, 405);
  }

  // Run everything as the caller (authenticated role) via their forwarded JWT.
  const authHeader = req.headers.get('Authorization') ?? '';
  const db = createClient(SUPABASE_URL, ANON_KEY, {
    global: { headers: { Authorization: authHeader } }
  });

  const {
    data: { user }
  } = await db.auth.getUser();
  if (!user) {
    return json({ error: 'Unauthorized' }, 401);
  }

  let payload: GeneratePayload;
  try {
    payload = (await req.json()) as GeneratePayload;
  } catch {
    return json({ error: 'Invalid JSON body' }, 400);
  }

  if (!payload.releaseNoteId || !payload.storagePath) {
    return json({ error: 'Missing releaseNoteId or storagePath' }, 400);
  }

  // RLS scopes this to the caller's own rows.
  const { data: note, error: noteError } = await db
    .from('release_notes')
    .select('id, status')
    .eq('id', payload.releaseNoteId)
    .maybeSingle();

  if (noteError) {
    return json({ error: 'lookup_failed', detail: noteError.message }, 500);
  }
  if (!note) {
    return json({ error: 'note_not_found', releaseNoteId: payload.releaseNoteId }, 404);
  }
  if (note.status !== 'generating') {
    return json({ error: 'wrong_status', status: note.status }, 409);
  }

  // Do the slow work after responding.
  EdgeRuntime.waitUntil(runGeneration(db, payload));

  return json({ accepted: true, releaseNoteId: payload.releaseNoteId }, 202);
});
